public class CalloutConstant {
    public static final String TRAILHEAD_ME = 'https://trailblazer.me/id/';
    public static final String TRAILHEAD_ME_USERID = 'https://trailblazer.me/id?cmty=trailhead&uid=';
    public static final String GO_TRAILHEAD_API = 'https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/';
    public static final String JOB_NAME = 'Populate Trailblazers from GetTrailblazerInfoAsync';
    public static final String PROFILE_PATH = '/profile';
    public static final String SUPERBADGES_PATH = '/badges/superbadge';
    public static final String BADGES_PATH = '/badges';
    public static final String CERTIFICATIONS_PATH = '/certifications';
    public static final String HEROKU_ERROR = 'Application error';
    public static final String SUCCESS = 'success';
}
